# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0.xci
# IP: The module: 'base_timer_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0.xci
# IP: The module: 'base_timer_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/eashanw/Audio_open/audio-revamp-soc/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_1_0/base_timer_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
